version: 1

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/why-go-over
    binary: why-go-over
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: false

archives:
  - files:
      - LICENSE
      - README.md
      - CHANGELOG.md

#snapshot:
#  name_template: "{{ .Env.NIGHTLY_VERSION }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
